/* Schools Annual Examination Papers - Data Analysis Mini-project */

DROP SEQUENCE IF EXISTS "roll_number_seq" CASCADE
;
CREATE SEQUENCE "roll_number_seq"
	start 10001
;

DROP TABLE IF EXISTS "tblStudents"
;
CREATE TABLE IF NOT EXISTS "tblStudents"
(
	  roll_number integer PRIMARY KEY DEFAULT nextval('"roll_number_seq"')
	, student_name varchar(90)
	, class varchar(2)
	, section varchar(2)
	, school_name varchar(90)
)
;

ALTER SEQUENCE "roll_number_seq" OWNED BY "tblStudents"."roll_number";

INSERT INTO "tblStudents"(student_name, class, section, school_name) VALUES
  ('Abhijit', '6', 'A', 'Google Public School')
,   ('Aghat', '6', 'A', 'Google Public School')
,   ('Amitava Chandar', '6', 'A', 'Google Public School')
,   ('Anbarasu', '6', 'A', 'Google Public School')
,   ('Atralarasu', '6', 'A', 'Google Public School')
,   ('Ayog', '6', 'A', 'Google Public School')
,   ('Bhishma', '6', 'A', 'Google Public School')
,   ('Dwaipayan', '6', 'A', 'Google Public School')
,   ('Ekalinga', '6', 'A', 'Google Public School')
,   ('Gulfam', '6', 'A', 'Google Public School')
,   ('Harjeet', '6', 'A', 'Google Public School')
,   ('Ibhanan', '6', 'A', 'Google Public School')
,   ('Irfan', '6', 'A', 'Google Public School')
,   ('Jnyaneshwar', '6', 'A', 'Google Public School')
,   ('Kamadev', '6', 'A', 'Google Public School')
,   ('Lokesh', '6', 'A', 'Google Public School')
,   ('Naman', '6', 'A', 'Google Public School')
,   ('Namdev', '6', 'A', 'Google Public School')
,   ('Nanak', '6', 'A', 'Google Public School')
,   ('Nikhilesh', '6', 'A', 'Google Public School')
,   ('Nitish', '6', 'A', 'Google Public School')
,   ('Rupin', '6', 'A', 'Google Public School')
,   ('Sambhav', '6', 'A', 'Google Public School')
,   ('Sanam', '6', 'A', 'Google Public School')
,   ('Shubhendu', '6', 'A', 'Google Public School')
,   ('Swaminath', '6', 'A', 'Google Public School')
,   ('Tamonash', '6', 'A', 'Google Public School')
,   ('Tanveer', '6', 'A', 'Google Public School')
,   ('Unnikrishnan', '6', 'A', 'Google Public School')
,   ('Vaijnath', '6', 'A', 'Google Public School')
,   (' Rishika', '6', 'B', 'Google Public School')
,   ('Amod', '6', 'B', 'Google Public School')
,   ('Arnav', '6', 'B', 'Google Public School')
,   ('Badal Tyagi', '6', 'B', 'Google Public School')
,   ('Bhargava', '6', 'B', 'Google Public School')
,   ('Gopichand', '6', 'B', 'Google Public School')
,   ('Japa Hiten', '6', 'B', 'Google Public School')
,   ('Jayashekhar', '6', 'B', 'Google Public School')
,   ('Lalitkishore', '6', 'B', 'Google Public School')
,   ('Loknath', '6', 'B', 'Google Public School')
,   ('Mandhatri', '6', 'B', 'Google Public School')
,   ('Mangesh', '6', 'B', 'Google Public School')
,   ('Mubarak', '6', 'B', 'Google Public School')
,   ('Murari', '6', 'B', 'Google Public School')
,   ('Niral', '6', 'B', 'Google Public School')
,   ('Prajesh Modi', '6', 'B', 'Google Public School')
,   ('Raj', '6', 'B', 'Google Public School')
,   ('Rajeev', '6', 'B', 'Google Public School')
,   ('Ratan', '6', 'B', 'Google Public School')
,   ('Santawana', '6', 'B', 'Google Public School')
,   ('Shailendra', '6', 'B', 'Google Public School')
,   ('Shridevi', '6', 'B', 'Google Public School')
,   ('Shubhangi', '6', 'B', 'Google Public School')
,   ('Sunirmal', '6', 'B', 'Google Public School')
,   ('Taruntapan', '6', 'B', 'Google Public School')
,   ('Usha', '6', 'B', 'Google Public School')
,   ('Ananya Sachin', '6', 'C', 'Google Public School')
,   ('Arpana', '6', 'C', 'Google Public School')
,   ('Bhagyashree', '6', 'C', 'Google Public School')
,   ('Chaitali', '6', 'C', 'Google Public School')
,   ('Chandrabhaga', '6', 'C', 'Google Public School')
,   ('Gurjari', '6', 'C', 'Google Public School')
,   ('Jalabala', '6', 'C', 'Google Public School')
,   ('Juily', '6', 'C', 'Google Public School')
,   ('Kuntala', '6', 'C', 'Google Public School')
,   ('Manikuntala', '6', 'C', 'Google Public School')
,   ('Mausumi', '6', 'C', 'Google Public School')
,   ('Mayura', '6', 'C', 'Google Public School')
,   ('Nazima', '6', 'C', 'Google Public School')
,   ('Nityapriya', '6', 'C', 'Google Public School')
,   ('Preeti', '6', 'C', 'Google Public School')
,   ('Ratnavali', '6', 'C', 'Google Public School')
,   ('Rupashi', '6', 'C', 'Google Public School')
,   ('Saudamini', '6', 'C', 'Google Public School')
,   ('Shabari', '6', 'C', 'Google Public School')
,   ('Shaheena', '6', 'C', 'Google Public School')
,   ('Sharika', '6', 'C', 'Google Public School')
,   ('Shobhana', '6', 'C', 'Google Public School')
,   ('Subhashini', '6', 'C', 'Google Public School')
,   ('Sudeepa', '6', 'C', 'Google Public School')
,   ('Uditi', '6', 'C', 'Google Public School')
,   ('Vritti', '6', 'C', 'Google Public School')
,   ('Alisa', '7', 'A', 'Google Public School')
,   ('Amala Nageshwar', '7', 'A', 'Google Public School')
,   ('Banamala', '7', 'A', 'Google Public School')
,   ('Charu', '7', 'A', 'Google Public School')
,   ('Chinmayi', '7', 'A', 'Google Public School')
,   ('Jack', '7', 'A', 'Google Public School')
,   ('Kaveri', '7', 'A', 'Google Public School')
,   ('Keshini', '7', 'A', 'Google Public School')
,   ('Lajwanti', '7', 'A', 'Google Public School')
,   ('Madaline', '7', 'A', 'Google Public School')
,   ('Max', '7', 'A', 'Google Public School')
,   ('Mriganayani', '7', 'A', 'Google Public School')
,   ('Mythily', '7', 'A', 'Google Public School')
,   ('Nupura', '7', 'A', 'Google Public School')
,   ('Olivia', '7', 'A', 'Google Public School')
,   ('Pragyawati', '7', 'A', 'Google Public School')
,   ('Sadhvi', '7', 'A', 'Google Public School')
,   ('Shreemayi', '7', 'A', 'Google Public School')
,   ('Stella', '7', 'A', 'Google Public School')
,   ('Sushma', '7', 'A', 'Google Public School')
,   ('Tilottama', '7', 'A', 'Google Public School')
,   ('Upama', '7', 'A', 'Google Public School')
,   ('Vanhishikha', '7', 'A', 'Google Public School')
,   ('Yaksha', '7', 'A', 'Google Public School')
,   ('Adelaide', '7', 'B', 'Google Public School')
,   ('Adelaide', '7', 'B', 'Google Public School')
,   ('Aldus', '7', 'B', 'Google Public School')
,   ('Amber', '7', 'B', 'Google Public School')
,   ('April', '7', 'B', 'Google Public School')
,   ('Charlotte', '7', 'B', 'Google Public School')
,   ('Derek', '7', 'B', 'Google Public School')
,   ('Dominik', '7', 'B', 'Google Public School')
,   ('Eric', '7', 'B', 'Google Public School')
,   ('Fiona', '7', 'B', 'Google Public School')
,   ('Freddie', '7', 'B', 'Google Public School')
,   ('Joyce', '7', 'B', 'Google Public School')
,   ('Justin', '7', 'B', 'Google Public School')
,   ('Kate', '7', 'B', 'Google Public School')
,   ('Kirsten', '7', 'B', 'Google Public School')
,   ('Kristian', '7', 'B', 'Google Public School')
,   ('Lana', '7', 'B', 'Google Public School')
,   ('Lily', '7', 'B', 'Google Public School')
,   ('Lydia', '7', 'B', 'Google Public School')
,   ('Martin', '7', 'B', 'Google Public School')
,   ('Olivia', '7', 'B', 'Google Public School')
,   ('Robert', '7', 'B', 'Google Public School')
,   ('Roland', '7', 'B', 'Google Public School')
,   ('Sam', '7', 'B', 'Google Public School')
,   ('Sydney', '7', 'B', 'Google Public School')
,   ('Tony', '7', 'B', 'Google Public School')
,   ('Vincent', '7', 'B', 'Google Public School')
,   ('Vincent', '7', 'B', 'Google Public School')
,   ('Albert', '7', 'C', 'Google Public School')
,   ('Amelia', '7', 'C', 'Google Public School')
,   ('Arianna', '7', 'C', 'Google Public School')
,   ('Arnold', '7', 'C', 'Google Public School')
,   ('Byron', '7', 'C', 'Google Public School')
,   ('Cadie', '7', 'C', 'Google Public School')
,   ('Catherine', '7', 'C', 'Google Public School')
,   ('Chloe', '7', 'C', 'Google Public School')
,   ('Clark', '7', 'C', 'Google Public School')
,   ('Derek', '7', 'C', 'Google Public School')
,   ('Eric', '7', 'C', 'Google Public School')
,   ('Henry', '7', 'C', 'Google Public School')
,   ('Jack', '7', 'C', 'Google Public School')
,   ('Julia', '7', 'C', 'Google Public School')
,   ('Kirsten', '7', 'C', 'Google Public School')
,   ('Maximilian', '7', 'C', 'Google Public School')
,   ('Miranda', '7', 'C', 'Google Public School')
,   ('Naomi', '7', 'C', 'Google Public School')
,   ('Olivia', '7', 'C', 'Google Public School')
,   ('Preston', '7', 'C', 'Google Public School')
,   ('Roland', '7', 'C', 'Google Public School')
,   ('Sawyer', '7', 'C', 'Google Public School')
,   ('Tess', '7', 'C', 'Google Public School')
,   ('William', '7', 'C', 'Google Public School')
,   ('Ada', '8', 'A', 'Google Public School')
,   ('Adam', '8', 'A', 'Google Public School')
,   ('Aldus', '8', 'A', 'Google Public School')
,   ('Aldus', '8', 'A', 'Google Public School')
,   ('Alina', '8', 'A', 'Google Public School')
,   ('Amy', '8', 'A', 'Google Public School')
,   ('Annabella', '8', 'A', 'Google Public School')
,   ('Cadie', '8', 'A', 'Google Public School')
,   ('Chloe', '8', 'A', 'Google Public School')
,   ('Chloe', '8', 'A', 'Google Public School')
,   ('Daniel', '8', 'A', 'Google Public School')
,   ('Eddy', '8', 'A', 'Google Public School')
,   ('Freddie', '8', 'A', 'Google Public School')
,   ('Frederick', '8', 'A', 'Google Public School')
,   ('Garry', '8', 'A', 'Google Public School')
,   ('George', '8', 'A', 'Google Public School')
,   ('Heather', '8', 'A', 'Google Public School')
,   ('Isabella', '8', 'A', 'Google Public School')
,   ('Luke', '8', 'A', 'Google Public School')
,   ('Lydia', '8', 'A', 'Google Public School')
,   ('Marcus', '8', 'A', 'Google Public School')
,   ('Martin', '8', 'A', 'Google Public School')
,   ('Paul', '8', 'A', 'Google Public School')
,   ('Paul', '8', 'A', 'Google Public School')
,   ('Roland', '8', 'A', 'Google Public School')
,   ('Roman', '8', 'A', 'Google Public School')
,   ('Ryan', '8', 'A', 'Google Public School')
,   ('Sarah', '8', 'A', 'Google Public School')
,   ('Valeria', '8', 'A', 'Google Public School')
,   ('William', '8', 'A', 'Google Public School')
,   ('Adelaide', '8', 'B', 'Google Public School')
,   ('Adele', '8', 'B', 'Google Public School')
,   ('Alberta', '8', 'B', 'Google Public School')
,   ('Arnold', '8', 'B', 'Google Public School')
,   ('Arnold', '8', 'B', 'Google Public School')
,   ('Blake', '8', 'B', 'Google Public School')
,   ('Chester', '8', 'B', 'Google Public School')
,   ('Chloe', '8', 'B', 'Google Public School')
,   ('Clark', '8', 'B', 'Google Public School')
,   ('Clark', '8', 'B', 'Google Public School')
,   ('Dale', '8', 'B', 'Google Public School')
,   ('Eleanor', '8', 'B', 'Google Public School')
,   ('Elian', '8', 'B', 'Google Public School')
,   ('Elise', '8', 'B', 'Google Public School')
,   ('Fenton', '8', 'B', 'Google Public School')
,   ('Florrie', '8', 'B', 'Google Public School')
,   ('Florrie', '8', 'B', 'Google Public School')
,   ('Henry', '8', 'B', 'Google Public School')
,   ('Honey', '8', 'B', 'Google Public School')
,   ('Lucas', '8', 'B', 'Google Public School')
,   ('Max', '8', 'B', 'Google Public School')
,   ('Michael', '8', 'B', 'Google Public School')
,   ('Michael', '8', 'B', 'Google Public School')
,   ('Naomi', '8', 'B', 'Google Public School')
,   ('Paige', '8', 'B', 'Google Public School')
,   ('Spike', '8', 'B', 'Google Public School')
,   ('Adelaide', '8', 'C', 'Google Public School')
,   ('Adrianna', '8', 'C', 'Google Public School')
,   ('Alan', '8', 'C', 'Google Public School')
,   ('Alexander', '8', 'C', 'Google Public School')
,   ('Alexander', '8', 'C', 'Google Public School')
,   ('Alina', '8', 'C', 'Google Public School')
,   ('Byron', '8', 'C', 'Google Public School')
,   ('Charlie', '8', 'C', 'Google Public School')
,   ('Dexter', '8', 'C', 'Google Public School')
,   ('Eddy', '8', 'C', 'Google Public School')
,   ('Emily', '8', 'C', 'Google Public School')
,   ('Heather', '8', 'C', 'Google Public School')
,   ('Henry', '8', 'C', 'Google Public School')
,   ('Jack', '8', 'C', 'Google Public School')
,   ('Julia', '8', 'C', 'Google Public School')
,   ('Justin', '8', 'C', 'Google Public School')
,   ('Kellan', '8', 'C', 'Google Public School')
,   ('Kirsten', '8', 'C', 'Google Public School')
,   ('Kirsten', '8', 'C', 'Google Public School')
,   ('Lucas', '8', 'C', 'Google Public School')
,   ('Melissa', '8', 'C', 'Google Public School')
,   ('Miller', '8', 'C', 'Google Public School')
,   ('Oliver', '8', 'C', 'Google Public School')
,   ('Oscar', '8', 'C', 'Google Public School')
,   ('Steven', '8', 'C', 'Google Public School')
,   ('Stuart', '8', 'C', 'Google Public School')
,   ('Tyler', '8', 'C', 'Google Public School')

;

/*
COMMIT
; 
*/
